允许通过DbField给特定field绑定convertor
troyzhxu/bean-searcher pull request #57
Opened 2022-07-04 06:11 UTC by tminglei

在复杂些的使用场景中，可能会存在相同的DbType绑定到不同的JavaType的情况，比如
- (db) json array 绑定到 (java) List<String>
- (db) json object 绑定到 (java) Map<String,String>

这种情况下很难使用公共配置的convertor，需要bean-searcher能支持针对不同的bean/field指定不同的convertor。

这个PR就是增加这种支持。

(注：我这边编码风格/方式未必贴合bean-searcher要求，如有不妥之处请批评指正)

2022-07-06 08:50 UTC, troyzhxu requested changes
1、特殊转换器的实例化
2、DbField 注解里指定的转换器用一个新的接口 Convertor 接口

2022-07-06 08:50 UTC, troyzhxu commented on bean-searcher/src/main/java/com/ejlchina/searcher/implement/DefaultBeanReflector.java
> +			FieldConvertor convertor = getFieldConvertor(meta.getConvClazz());
可以将 这个特殊转换器的实例化 过程 前置，放到 MetaResolver 里

2022-07-06 08:50 UTC, troyzhxu commented on bean-searcher/src/test/java/com/ejlchina/searcher/BeanRefactorTestCase.java
> +    public static class Json2MapConverter implements FieldConvertor.BFieldConvertor {
既然只需要一个方法，就新写一个接口吧：
```java
public interface Convertor {
    Object convert(FieldMeta meta, Object value)
}
```
然后原来的 `FieldConvertor ` 继承 `Convertor `
```java
public interface FieldConvertor extends Convertor  {
    boolean supports(FieldMeta meta, Class<?> valueType)
    Object convert(FieldMeta meta, Object value)
}
```

2022-07-07 08:21 UTC, tminglei commented on bean-searcher/src/main/java/com/ejlchina/searcher/implement/DefaultBeanReflector.java
> +			FieldConvertor convertor = getFieldConvertor(meta.getConvClazz());
OK

2022-07-07 08:21 UTC, tminglei commented on bean-searcher/src/test/java/com/ejlchina/searcher/BeanRefactorTestCase.java
> +    public static class Json2MapConverter implements FieldConvertor.BFieldConvertor {
👌🏻

2022-07-07 09:22 UTC, tminglei commented on bean-searcher/src/main/java/com/ejlchina/searcher/implement/DefaultBeanReflector.java
> +			FieldConvertor convertor = getFieldConvertor(meta.getConvClazz());
这个你再确认一下

2022-07-07 09:22 UTC, tminglei commented
针对第二点（DbField 注解里指定的转换器用一个新的接口 Convertor 接口）的调整已完成，第一点需要再确认一下。

2022-07-07 09:28 UTC, troyzhxu commented on bean-searcher/src/test/java/com/ejlchina/searcher/BeanRefactorTestCase.java
> +    public static class Json2MapConverter implements FieldConvertor.BFieldConvertor {
> 针对第二点（DbField 注解里指定的转换器用一个新的接口 Convertor 接口）的调整已完成，第一点需要再确认一下。

新类中注释中的 author 改成你自己哈

2022-07-07 14:16 UTC, troyzhxu commented on bean-searcher/src/main/java/com/ejlchina/searcher/implement/DefaultBeanReflector.java
> +			FieldConvertor convertor = getFieldConvertor(meta.getConvClazz());
因为 `DefaultBeanReflector` 里的 `Object convert(FieldMeta meta, Object value)`  方法的执行次数是 `N * M`（行数 * 列数） 次的，执行频率非常高，这样写的话就会有多了 `2 * N * M` 次 的哈希查找，虽然每次性能消耗都非常少，但次数多起来还是值得优化的。

2022-07-08 06:15 UTC, tminglei commented on bean-searcher/src/main/java/com/ejlchina/searcher/implement/DefaultBeanReflector.java
> +			FieldConvertor convertor = getFieldConvertor(meta.getConvClazz());
好的，听你的 👍

2022-07-08 06:15 UTC, tminglei commented on bean-searcher/src/test/java/com/ejlchina/searcher/BeanRefactorTestCase.java
> +    public static class Json2MapConverter implements FieldConvertor.BFieldConvertor {
好的

2022-07-08 06:32 UTC, tminglei commented
调整已完成，请再看一下

2022-07-14 01:59 UTC, merged